// <auto-generated />
using IISManager.Core.Infrastructure.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IISManager.Core.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.14");

            modelBuilder.Entity("IISManager.Core.Domain.Common.AppPoolGroup", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("AppPoolGroups");
                });

            modelBuilder.Entity("IISManager.Core.Domain.Common.AppPoolGroupAppPool", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppPoolGroupName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("AppPoolGroupName");

                    b.ToTable("AppPoolGroupAppPool");
                });

            modelBuilder.Entity("IISManager.Core.Domain.Common.AppPoolGroupAppPool", b =>
                {
                    b.HasOne("IISManager.Core.Domain.Common.AppPoolGroup", null)
                        .WithMany("AssignedAppPoolNames")
                        .HasForeignKey("AppPoolGroupName");
                });

            modelBuilder.Entity("IISManager.Core.Domain.Common.AppPoolGroup", b =>
                {
                    b.Navigation("AssignedAppPoolNames");
                });
#pragma warning restore 612, 618
        }
    }
}
